Algoritmo "Antecessor"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Receber um valor de um número e mostrar o Antecessor do número
// Autor(a)    : João Cristian
// Data atual  : 16/09/2024
Var
   numero,antecessor: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite um número")
   leia(numero)

   antecessor <- numero -1
   escreval("O antecessor do número digitado é: ", antecessor)

Fimalgoritmo