Algoritmo "area_Retangulo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Inserir um valor de base e altura de um retangúlo e mostrar a área total
// Autor(a)    : João Cristian
// Data atual  : 16/09/2024
Var
   // Seção de Declarações das variáveis
   base, altura, area:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Insira o valor da base do retângulo: ")
   leia(base)

   escreval("Insira o valor da altura do retângulo: ")
   leia(altura)

   area <- base * altura
   escreval("A área total do retângulo é: ", area)
Fimalgoritmo