Algoritmo "ImparesDe0A20"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Inserir um numero, retornar os números impares
// Autor(a)    : João Cristian
// Data atual  : 29/09/2024
Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   numero <- 0
   enquanto numero <= 20 faca
      se (numero mod 2) <> 0 entao
         escreval("Os números ímpares entre 0 e 20 são: ", numero)
      fimse
      numero <- numero + 1
   fimenquanto

Fimalgoritmo