Algoritmo "SomaCemPrimeirosNumeros"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Contador que faça a soma de primeiros números
// Autor(a)    : João Cristian
// Data atual  : 29/09/2024

Var
   // Seção de Declarações das variáveis
   contador, soma: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contador <- 0
   soma <- 0
   enquanto contador <= 100 faca
      soma <- soma + contador
      contador <- contador + 1
   fimenquanto
   escreval("A soma dos 100 primeiros números inteiros é: ", soma)

Fimalgoritmo