Algoritmo "Quadrado_Diferenca"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Inserir dois valores, retornar a diferença dos dois valores
// Autor(a)    : João Cristian
// Data atual  : 29/09/2024
Var
   // Seção de Declarações das variáveis
   valor1, valor2, resultado: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite primeiro valor: ")
   leia(valor1)
   escreval("Digite o segundo valor: ")
   leia(valor2)
   resultado <- (valor1 - valor2)^2
   escreval("O quadrado da diferença entre o primeiro valor e o segundo valor é de: ", resultado)

Fimalgoritmo