Algoritmo "Adicao_Multiplicacao_Distributiva"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Digitar os valores, A, B, C, D, retornar os resultados das somas e multiplicação de A, B, C, D
// Autor(a)    : João Cristian
// Data atual  : 29/09/2024
Var
   // Seção de Declarações das variáveis
   ValorA, valorB, valorC, valorD: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite o valor de A: ")
   leia(valorA)
   escreval("Digite o valor de B: ")
   leia(valorB)
   escreval("Digite o valor de C: ")
   leia(valorC)
   escreval("Digite o valor de D: ")
   leia(valorD)

   escreval("Resultado das Somas: ")
   escreval("A + B = ", valorA + valorB)
   escreval("A + C = ", valorA + valorC)
   escreval("A + D = ", valorA + valorD)
   escreval("B + C = ", valorB + valorC)
   escreval("B + D = ", valorB + valorD)
   escreval("C + D = ", valorC + valorD)

   escreval("Resultado das Multiplicações: ")
   escreval("A x B = ", valorA * valorB)
   escreval("A x C = ", valorA * valorC)
   escreval("A x D = ", valorA * valorD)
   escreval("B x C = ", valorB * valorC)
   escreval("B x D = ", valorB * valorD)
   escreval("C x D = ", valorC * valorD)


Fimalgoritmo