Algoritmo "soma_dos_quadrados"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Insira valores, A, B, C, retornar o quadrado soma
// Autor(a)    : João Cristian
// Data atual  : 29/09/2024
Var
   // Seção de Declarações das variáveis
   valorA, valorB, valorC, quadradoSoma : real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite o valor de A: ")
   leia(valorA)
   escreval("Digite o valor de B: ")
   leia(valorB)
   escreval("Digite o valor de C: ")
   leia(valorC)
   quadradoSoma  <- (ValorA + ValorB + ValorC) ^ 2
   escreval("O quadrado da soma de A, B e C é: ", quadradoSoma)

Fimalgoritmo