Algoritmo "soma_dos_quadrados"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Inserir os valores, A, B, C, retornar a soma dos quadrados
// Autor(a)    : João Cristian
// Data atual  : 29/09/2024
Var
   // Seção de Declarações das variáveis
   valorA, valorB, valorC, soma_quadrados: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite o valor de A: ")
   leia(valorA)
   escreval("Digite o valor de B: ")
   leia(valorB)
   escreval("Digite o valor de C: ")
   leia(valorC)
   soma_quadrados <- (ValorA^2) + (ValorB^2) + (ValorC^2)
   escreval("A soma dos quadrados de A, B e C é: ", soma_quadrados)

Fimalgoritmo