Algoritmo "ValoresImpares"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Mostrar todos os valores impares de 0 a 20
// Autor(a)    : João Cristian
// Data atual  : 29/09/2024
Var
   // Seção de Declarações das variáveis
   contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contador de 0 ate 20 faca
      se (contador mod 2) <> 0 entao
         escreval("Os valores ímpares são: ", contador)
      fimse
   fimpara
Fimalgoritmo