Algoritmo "SerieFibonacci"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Calcule e apresenta apresenta a série de Fibonacci até o décimo quinto termo.
// Autor(a)    : João Cristian
// Data atual  : 29/09/2024
Var
   // Seção de Declarações das variáveis
   valor1, valor2, proximoTermo, contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   valor1 <- 1
   valor2 <- 1
   escreval(valor1)
   escreval(valor2)
   para contador de 3 ate 15 faca
      proximoTermo <- valor1 + valor2
      escreval(proximoTermo)
      valor1 <- valor2
      valor2 <- proximoTermo
   fimpara
Fimalgoritmo