Algoritmo "tabuada"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Inserir um número, realizar a tabuada
// Autor(a)    : João Cristian
// Data atual  : 29/09/2024
Var
   // Seção de Declarações das variáveis
   numero, contador, resultado: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite o número para realizar a tabuada: ")
   leia(numero)
   para contador de 0 ate 10 faca
      resultado <- numero * contador
      escrevaL(numero, " x ", contador, " = ", resultado)
   fimpara

Fimalgoritmo