Algoritmo "QuadradoDosNumeros"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Calcule e apresenta os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : João Cristian
// Data atual  : 29/09/2024
Var
// Seção de Declarações das variáveis 
 contador, quadrado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  para contador de 15 ate 200 faca
        quadrado <- contador * contador
        escreval("O quadrado de ", contador, " é: ", quadrado)
  fimpara
Fimalgoritmo