Algoritmo "Soma_Cem_Numeros"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Calcule e apresenta a soma dos cem primeiros números inteiros.
// Autor(a)    : João Cristian
// Data atual  : 29/09/2024
Var
   // Seção de Declarações das variáveis
   contador, soma: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   soma <- 0
   para contador de 1 ate 100 faca
      soma <- soma + contador
   fimpara
   escreval("A soma dos 100 primeiros números inteiros é: ", soma)
Fimalgoritmo