Algoritmo "maior_menor"
// Disciplina   : [ Lógica de Programação com JavaSript]
// Professor   : Jailson
// Descrição   : Inserir um valor de um número, retornar se é maior que 10
// Autor(a)    : João Cristian
// Data atual  : 18/09/2024
Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite um número: ")
   leia(numero)
   se (numero >= 10) entao
      escreval("Número é maior que 10")
   senao
      escreval("Número é menor que 10")
   fimse


Fimalgoritmo