Algoritmo "positivo_negativo"
// Disciplina   : [ Lógica de Programação com JavaSript]
// Professor   : Jailson
// Descrição   : inserir um valor, retornar se é positivo ou negativo
// Autor(a)    : João Cristian
// Data atual  : 18/09/2024
Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Insira um número: ")
   leia(numero)

   se numero > 0 entao
      escreval("O número é positivo")
   senao
      escreval("O número é negativo")
   fimse

Fimalgoritmo